theme: jekyll-theme-minimal
title: Raffaello Paletta
description: "Senior Software Engineer<br/><br/>
<a href='#'>Oct 2017 - Present</a><br/>
<a href='#'>Apr 2009 - Oct 2017</a><br/>
"
logo: /assets/img/avatar.png
